---
packages:
  # required to boot
  - linux
  - base
  - base-devel
  # virtual devices
  - cryptsetup
  - btrfs-progs
  # miscellaneous
  - git
  - neovim
  - flatpak
  - chezmoi
  - sudo
  - python
  - man
  - tldr
  - usbutils # lsusb
  - zsh
  - direnv
  - zip
  - unzip
  - fzf
  - htop
  - devtools

  # network
  - dhcpcd
  - openssh
  # security
  - apparmor

dev_packages:
  # ARM
  - arm-none-eabi-binutils
  - arm-none-eabi-gcc
  - arm-none-eabi-newlib
  # C
  - cmake
  - gcc
  - clang
  # virtualisation
  - docker
  - docker-compose
  - ansible
  # other
  - ffmpeg
  - nodejs
  - zig
  - rust
  - ocaml
  - ghc
  - go
# nvim
  - python-pylatexenc
  

wireless_packages:
  - networkmanager
  - wpa_supplicant
