---
packages:
  - greetd
  - greetd-tuigreet
  # base
  - hyprland
  - hyprpaper
  - xdg-desktop-portal-hyprland
  - polkit-kde-agent
  - wl-clipboard
  - mpd  # todo: start/ enable daemon
  - playerctl
  - brightnessctl
  - grim # grim and slurp for screenshot
  - slurp
  - atuin
  - pulseaudio
  - pulseaudio-bluetooth
  - bluez
  
  # else
  - mako # notification daemon
  - pipewire
  - polkit-kde-agent # if not used, remove start in hyprland config
  # applications
  - rofi-wayland
  - rofimoji
  - waybar
  - swaylock
  - alacritty
  - zellij
  - firefox
  - syncthing
  # fonts
  - gnu-free-fonts
  - otf-font-awesome
  - ttf-iosevkaterm-nerd
  - adobe-source-han-sans-cn-fonts
  # latex compile
  - texlive-meta
  - zathura

flatpak_packages:
  - com.discordapp.Discord
  - com.github.xournalpp.xournalpp
  - com.obsproject.Studio
  - com.valvesoftware.Steam
  - md.obsidian.Obsidian
  - info.beyondallreason.bar
  - org.blender.Blender
  - org.godotengine.Godot
  - org.inkscape.Inkscape
  - org.kde.elisa
  - org.kde.krita
  - org.libreoffice.LibreOffice 
  - org.openscad.OpenSCAD
  - org.signal.Signal
  - org.yuzu_emu.yuzu
  - net.ankiweb.Anki

dependencies:
  - gsound
autologin: true
autologin_session: hyprland
